/**
 * babelForge — single source of truth for design tokens.
 *
 * Every color the app renders flows from this file. Consumers:
 *   - tailwind.config.ts (build-time theme.extend.colors)
 *   - lib/theme/cssVars.ts (runtime CSS custom properties injected by layout)
 *   - lib/signal/bands.ts (EEG band palette)
 *   - lib/engine/topology.ts (Yeo brain network colors)
 *   - components/fourier/SpectrumCanvas (canvas-rendered axes/peaks)
 *   - components/NeuroCanvas (three.js material seeds)
 *
 * Rationale: previously colors were duplicated as hex literals across
 * tailwind config, globals.css, bands.ts, REGION_COLOR, and ad-hoc canvas
 * draws. Drift was inevitable. The engine computes every shade from a small
 * set of base hues so a palette tweak propagates everywhere automatically.
 *
 * Design philosophy: clinical, calm, AAA-readable on dark surfaces.
 *   - Background = slate-navy (not pure black) to reduce sustained glare.
 *   - Foreground = soft warm-white (not #fff) to drop contrast from
 *     dazzling 21:1 to a comfortable ~14:1.
 *   - Accent = desaturated cobalt (220° H) — calmer than electric blue,
 *     reads as authoritative without screaming.
 *   - Status (ok/warn/crit) shifted off pure emerald/amber/red toward
 *     teal/honey/coral so they don't fight the cobalt accent.
 *   - EEG bands span the visible spectrum (purple→amber) so frequency
 *     ordinality is preserved visually.
 */

import { hexToHsl, hslToHex, ramp, type HSL } from "./color";

// ---------------------------------------------------------------------------
// Base hues — every other token is derived from these eight anchors.
// ---------------------------------------------------------------------------

const BASE = {
  canvas: hexToHsl("#0d1117"), // slate-navy, GitHub-dark adjacent
  ink: hexToHsl("#d4dae5"),    // warm off-white
  accent: hexToHsl("#4d8dff"), // calm cobalt (220°)
  ok: hexToHsl("#34c997"),     // sage teal
  warn: hexToHsl("#f0b154"),   // honey amber
  crit: hexToHsl("#ef5765"),   // soft coral
  info: hexToHsl("#4dc9dd"),   // glacier cyan
} as const;

// ---------------------------------------------------------------------------
// Surface ramp — derived from the canvas hue, lightness-stepped manually so
// the elevations stay close together (high-tonal-density UIs need < 4% L
// between adjacent surfaces or the layering disappears).
// ---------------------------------------------------------------------------

const surfaceL = [0.07, 0.09, 0.11, 0.13, 0.16, 0.20, 0.26, 0.32];
const surface = surfaceL.reduce<Record<number, string>>((acc, l, i) => {
  const tier = [0, 50, 100, 200, 300, 400, 500][i] ?? 500;
  acc[tier] = hslToHex({ h: BASE.canvas.h, s: BASE.canvas.s, l });
  return acc;
}, {});

// ---------------------------------------------------------------------------
// Ink ramp — single hue, four lightness tiers. Designed so subtle/muted
// remain legible against surface 50–200 without bleaching out.
// ---------------------------------------------------------------------------

const ink = {
  DEFAULT: hslToHex(BASE.ink),
  subtle: hslToHex({ ...BASE.ink, l: 0.66 }),
  muted: hslToHex({ ...BASE.ink, l: 0.48 }),
  dim: hslToHex({ ...BASE.ink, l: 0.32 }),
};

// ---------------------------------------------------------------------------
// Lines / borders — same hue family as canvas, two tiers.
// ---------------------------------------------------------------------------

const line = {
  DEFAULT: hslToHex({ h: BASE.canvas.h, s: BASE.canvas.s, l: 0.17 }),
  strong: hslToHex({ h: BASE.canvas.h, s: BASE.canvas.s, l: 0.24 }),
};

// ---------------------------------------------------------------------------
// Accent ramp — generated by the engine. 50..700 covers tints (chips),
// 500 (default), and shades (hover/pressed).
// ---------------------------------------------------------------------------

const accent = ramp(BASE.accent, [50, 200, 400, 500, 600, 700]);

// ---------------------------------------------------------------------------
// EEG band palette — five hues stepped around the wheel so frequency
// monotonicity (δ→γ = slow→fast) maps onto wavelength (long→short).
// Derived from a single saturation/lightness target so swatches feel
// like siblings, not strangers.
// ---------------------------------------------------------------------------

const bandHue = { delta: 282, theta: 240, alpha: 195, beta: 155, gamma: 40 } as const;
const BAND_S = 0.62;
const BAND_L = 0.62;
const bands = {
  delta: hslToHex({ h: bandHue.delta, s: BAND_S, l: BAND_L }),
  theta: hslToHex({ h: bandHue.theta, s: BAND_S, l: BAND_L }),
  alpha: hslToHex({ h: bandHue.alpha, s: BAND_S, l: BAND_L }),
  beta: hslToHex({ h: bandHue.beta, s: BAND_S, l: BAND_L }),
  gamma: hslToHex({ h: bandHue.gamma, s: BAND_S, l: BAND_L }),
} as const;

// ---------------------------------------------------------------------------
// Yeo brain network palette — six networks, evenly spaced in hue so
// neighboring parcels are perceptually distinguishable at 3D render scale.
// ---------------------------------------------------------------------------

const regionHue = {
  Default: 230,     // indigo — DMN
  Control: 175,     // teal   — frontoparietal control
  Limbic: 38,       // amber  — limbic
  Visual: 290,      // violet — visual cortex
  SomatoMotor: 145, // green  — sensorimotor
  VentAttn: 0,      // rose   — ventral attention / salience
} as const;
const REGION_S = 0.58;
const REGION_L = 0.62;
const regions: Record<keyof typeof regionHue, string> = {
  Default: hslToHex({ h: regionHue.Default, s: REGION_S, l: REGION_L }),
  Control: hslToHex({ h: regionHue.Control, s: REGION_S, l: REGION_L }),
  Limbic: hslToHex({ h: regionHue.Limbic, s: REGION_S, l: REGION_L }),
  Visual: hslToHex({ h: regionHue.Visual, s: REGION_S, l: REGION_L }),
  SomatoMotor: hslToHex({ h: regionHue.SomatoMotor, s: REGION_S, l: REGION_L }),
  VentAttn: hslToHex({ h: regionHue.VentAttn, s: REGION_S, l: REGION_L }),
};

// ---------------------------------------------------------------------------
// Frozen palette object — the public API.
// ---------------------------------------------------------------------------

export const palette = {
  canvas: hslToHex(BASE.canvas),
  surface,
  ink,
  line,
  accent,
  ok: hslToHex(BASE.ok),
  warn: hslToHex(BASE.warn),
  crit: hslToHex(BASE.crit),
  info: hslToHex(BASE.info),
  bands,
  regions,
} as const;

export type Palette = typeof palette;

/** Expose base HSLs so consumers can derive their own variants. */
export const baseHsl: Record<keyof typeof BASE, HSL> = {
  canvas: BASE.canvas,
  ink: BASE.ink,
  accent: BASE.accent,
  ok: BASE.ok,
  warn: BASE.warn,
  crit: BASE.crit,
  info: BASE.info,
};
